[build-system]
requires = [
  "setuptools>=61.0.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "pytest-ctrf-json-reporter"
description = "Pytest CTRF Support"
version = "0.1"
readme = "README.rst"
requires-python = ">=3.8"
authors = [
    { name = "Benjamin Sinclair", email = "benjaminpsinclair@icloud.com" },
]
maintainers = [
    { name = "Benjamin Sinclair", email = "benjaminpsinclair@icloud.com" },
]
license = {file = "LICENSE"}
classifiers = [
    "Framework :: Pytest",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Testing",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "License :: OSI Approved :: MIT License",
]
dependencies = [
    "pytest>=6.2.0",
]
[project.urls]
Repository = "https://github.com/benjaminpsinclair/pytest-ctrf-json-reporter"
[project.entry-points.pytest11]
ctrf-json-reporter = "pytest_ctrf_json_reporter.plugin"
